### ISSUE TITLE
Board Prototype 1 Issues

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Hardware#1]
Potential leakage through R45 if battery cutoff is active but power switch is on. Leakage of 220K us ~16uA, so either increase this resistor, or rework the power section a bit

**Comment by mattbrejza** [comment]
footprint for microsd is slightly wrong

**Comment by mattbrejza** [comment]
footprint for smps inductor is too big

**Comment by dpslwk** [comment]
No longer an issue
