### ISSUE TITLE
Prototype -> Production Changes

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Hardware#2]
Consider replacing 0R with solder jumpers

**Comment by mattbrejza** [comment]
Change groups of resistors from individual resistors to resistor networks

**Comment by mattbrejza** [comment]
Change the microsd card holder to a cheaper one

**Comment by mattbrejza** [comment]
Consider changing the microusb to a more secure one (potentially partly through-hole)

**Comment by dpslwk** [comment]
No longer an issue
