### ISSUE TITLE
Prototype 2 Issues

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Hardware#3]
Check if WS2812 is fine on 3.3V, otherwise move to Vbat

**Comment by mattbrejza** [comment]
LGA12/LGA14 footprints mirrored

**Comment by mattbrejza** [comment]
Add option to bypass battery protection if not fitted

**Comment by mattbrejza** [comment]
change the microsd combo footprint's solder mask for the final selected part

**Comment by mattbrejza** [comment]
add soldermask to most of the wifi antenna pad

**Comment by dpslwk** [comment]
Here's what a have so far from the hand place

Mk3 build notes

Remove cream from tag connector
Speaker to close to the edge 
Larger stop around mcu and fpc connector pads, or make sure board house removes fingers
S5 J3 move names outside parts
Servo squiggle to small, 0.15-0.3 min thickness and clearance 
Remove silk on jag header, add pin 1 mark
Ic7 name and thicker silk
Test pad names on silk, check/add more
Header pin function labels need moving away from numbers
Rotate c42-40 labels
Round corners on lcd ribbon slot, use 2mm wire as template in milling layer
Duplicate conductive pad labels to both sides
Check meander on usb trace 
Remove place silk from 0603s
Ant pad, less exposed copper and cream
X3 is long way from mcu, check ok
R9 label rotate
R31 label rotate
~~Can we get ic4 in something other than msop-10?~~ Nope
Teardrops on final board, do some test runs on copy of brd file
Ic7 label
Lga14 footprint wrong on ic8
Don't like combined SD footprint, needs work
Q1 pin one mark bigger
D2 and D3 need values in schematic

'RepRap' Matt

**Comment by mattbrejza** [comment]
consider switching PA5 and PE11 for DAC on external headers

**Comment by mattbrejza** [comment]
consider connecting WS2812 to a timer pin

**Comment by dpslwk** [comment]
Missing drill hole for screen mounting/location peg

‘RepRap’ Matt

**Comment by dpslwk** [comment]
Move the CC serial header so its not under the screen
Move A, B LEDs away from screen 
Increase screen slik outline line thickness to 0.15mm
Make sure no silk labels are under screen ribbon (CC serial header is right now)
Add reset button for STM?

‘RepRap’ Matt

**Comment by dpslwk** [comment]
![screen shot 2016-05-19 at 11 16 11](https://cloud.githubusercontent.com/assets/234460/15390317/2d74b310-1db3-11e6-98ca-508e2834337a.png)

Cutout example for screen ribbon

**Comment by mattbrejza** [comment]
round corners near 3.3V/0V holes more 

![screen shot 2016-05-19 at 11 50 51](https://cloud.githubusercontent.com/assets/234460/15391230/fe6f0ff2-1db7-11e6-82f3-65bbfee34f97.png)
Example

**Comment by mattbrejza** [comment]
remove HSE and wire touchscreen

**Comment by mattbrejza** [comment]
switch A/B and joystick

**Comment by Jonty** [comment]
find wurth electronik passives we can swap in

**Comment by mattbrejza** [comment]
move 5mm LED more inwards

**Comment by mattbrejza** [comment]
look at buzzer options

**Comment by dpslwk** [comment]
thinking we should move the LED to the bottom of the board/below the SD socket, so its not in you hand when you hold the badge

**Comment by mattbrejza** [comment]
fiducials in opposite corners

**Comment by dpslwk** [comment]
do something with the 11 way connectors so they are in something we can buy and does not need modifying
pin header socket size are normally  2,3,4,5,6,8,10.15,16,20,25

**Comment by mattbrejza** [comment]
change footprints of microusb, switches to final ones

**Comment by mattbrejza** [comment]
consider only having tagconnect

**Comment by dpslwk** [comment]
Keep the SWD JTAG, not everyone can afford a Tag connect as well as a debugger
We are not populating it but might buy ~100 headers and sell them 

'RepRap' Matt

**Comment by dpslwk** [comment]
6x6 Tac switch foot print could have smaller pads and a little closer together
also add fancy alps pads just in case

‘RepRap’ Matt

**Comment by dpslwk** [comment]
See if we can get a Plastic lanyard clip sample asap and then check the  clip size and what hole it will need. 

'RepRap' Matt

**Comment by mattbrejza** [comment]
if connecting touchscreen, make sure goes to ADC2, leaving ADC1 for user

**Comment by mattbrejza** [comment]
add testpoints to parallel control sigs + one data

**Comment by mattbrejza** [comment]
increase resistor for charge LED

**Comment by mattbrejza** [comment]
mark on the silk where to place the velcro for the battery

**Comment by mattbrejza** [comment]
Comments moved to other issues
