### ISSUE TITLE
Board 2 Issues - Outline, stop, footprints,  misc

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Hardware#4]
| Item | Notes | Progress |
| --- | --- | --- |
| Teardrops on final board, do some test runs on copy of brd file |  |  |
| Ant pad, less exposed copper and cream |  | ✔ |
| Round corners on lcd ribbon slot, use 2mm wire as template in milling layer |  | ✔ |
| Don't like combined SD footprint, needs work | Will fix once decided on final part | ✔ |
| round corners near 3.3V/0V holes more | MB - I think they're fine | ✔ |
| round corners near USB/wifi more |  | ✔ |
| Missing drill hole for screen mounting/location peg | what size drill? (see comment) | ✔ |
| fiducials in opposite corners |  | LWK check please ✔ |
| Larger stop around mcu and fpc connector pads, or make sure board house removes fingers |  |  |
| change footprints of microusb, switches to final ones |  | ✔ |
| Remove cream from tag connector | I think just a dpcbs stencil 'artifact' | ✔ Confirmed, no action needed |
| find wurth electronik passives we can swap in |  | ✔ |
| 6x6 Tac switch foot print could have smaller pads and a little closer together also add fancy alps pads just in case |  | ✔ |
| See if we can get a Plastic lanyard clip sample asap and then check the  clip size and what hole it will need. |  |  |
| LWK to review LGA footprint pad/cream sizes | Make sure there not too small |  |
| Finalize battery connector selection. Suggest looking at JST PA (locking pin, less wire stress |  | PH fine ✔ |
| rename net TIM1_CH1N to TIM8_CH2 (for LED FET) |  | ✔ |

**Comment by mattbrejza** [comment]
Example image of screen peg: https://www.dropbox.com/s/eqn3t87pvbxqiao/IMG_4801.jpg?dl=0

**Comment by dpslwk** [comment]
No longer an issue
