### ISSUE TITLE
Board 2 Issues - Silk

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Hardware#6]
| Item | Notes | Progress |
| --- | --- | --- |
| Ic7 name and thicker silk |  | ✔ |
| Rotate c42-40 labels |  | ✔ |
| R9 label rotate; R31 label rotate |  | ✔ |
| Ic7 label |  | ✔ |
| Increase screen slik outline line thickness to 0.15mm |  | ✔ |
| Remove place silk from 0603s | MB disagrees | ✔ |
| Test pad names on silk |  | ✔ |
| Servo squiggle too small, 0.15-0.3 min thickness and clearance |  | ✔ |
| S5 J3 move names outside parts |  | ✔ |
| Duplicate conductive pad labels to both sides |  | ✔ |
| Q1 pin one mark bigger |  | ✔ |
| Make sure no silk labels are under screen ribbon (CC serial header is right now) |  | ✔ |
| Header pin function labels need moving away from numbers |  | ✔ |
| Remove silk on jtag header, add pin 1 mark |  | ✔ |
| mark on the silk where to place the velcro for the battery |  |  |
| Add XYZ indicator for IMU |  |  |
| Add label to stm32 rst |  |  |

**Comment by dpslwk** [comment]
No longer an issue
