### ISSUE TITLE
Board 2 Issues - Placement and Routing

### ISSUE THREAD

**Issue by mattbrejza** [emfcamp/Mk3-Hardware#7]
| Item | Notes | Progress |
| --- | --- | --- |
| LGA12/LGA14 footprints mirrored | Re-routing also needed | ✔ |
| switch A/B and joystick |  | ✔ |
| Add option to bypass battery protection if not fitted |  | ✔ |
| remove HSE and wire touchscreen | touchscreen not yet confirmed. if connecting touchscreen, make sure goes to ADC2, leaving ADC1 for user | ✔ |
| thinking we should move the LED to the bottom of the board/below the SD socket, so its not in you hand when you hold the badge; move 5mm LED more inwards |  | ✔ |
| Move A, B LEDs away from screen |  | ✔ |
| Add reset button for STM? | same switch as MENU? | ✔ |
| X3 is long way from mcu, check ok |  | ✔ - its only 32kHz, and not that far |
| Can we get ic4 in something other than msop-10? |  | ✔ nope |
| Test pad  add more | add testpoints to parallel control sigs + one data ✔ |  |
| Speaker too close to the edge |  | ✔ |
| Move the CC serial header so its not under the screen |  |  |
| consider switching PA5 and PE11 for DAC on external headers |  | ✔ |
| consider connecting WS2812 to a timer pin |  | ✔ |
| do something with the 11 way connectors so they are in something we can buy and does not need modifying pin header socket size are normally 2,3,4,5,6,8,10.15,16,20,25 |  |  |
| Check if WS2812 is fine on 3.3V, otherwise move to Vbat |  | ✔ |
| Check meander on usb trace |  | ✔ close enough |
| Battery option 3 |  | ✔ |
| R23 sort out |  | ✔ |
| Test point on CC_HIB |  | ✔ |

**Comment by dpslwk** [comment]
No longer an issue
